[tool.poetry]
name = "emotion-classification-langgraph"
version = "0.1.0"
description = ""
authors = ["Nils Kl√ºwer <n_klue@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
langgraph = "^0.1.9"
langchain = "^0.2.9"
langchain-community = "^0.2.7"
langchain-openai = "^0.1.17"
python-dotenv = "^1.0.1"
pandas = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
