[project]
name = "transcription-gemini"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.5"
dependencies = [
    "google-genai>=1.2.0",
    "ipykernel>=6.29.5",
    "ruff>=0.9.6",
]
